include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: true
    - avoid_unnecessary_containers: true
    - avoid_web_libraries_in_flutter: true
    - no_logic_in_create_state: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - prefer_single_quotes: true
    - sized_box_for_whitespace: true
